# DVDH Live Signal Analysis Dashboard
# Streamlit Optimized Skeleton v1.0
# Purpose: Diagnostic-only observational geometry analysis
# License: MIT

import time
import random
import streamlit as st
import datetime
import math
import os
import smtplib
import ssl
from email.message import EmailMessage
from countdown import get_countdown_state
import requests

# =============================
# Page Configuration
# =============================
st.set_page_config(
    page_title="DVDH Live Signal Dashboard",
    layout="wide"
)

# =============================
# Header
# =============================
st.title("🌌 DVDH Live Signal Analysis Dashboard")
st.subheader("Transforming Theories, Illuminating Singularities")

st.markdown(
    """
    **Scope Notice**  
    Diagnostic visualization only.  
    No observational or physical claims are asserted.
    """
)

st.divider()

# =============================
# Countdown (Cached-safe)
# =============================
@st.cache_data(ttl=60)
def countdown_state_cached():
    return get_countdown_state()

st.header("⏳ Observation Countdown")

state = countdown_state_cached()

if state["state"] == "PRE_WINDOW":
    st.metric(
        "Status (UTC)",
        "PRE-WINDOW",
        f"{state['days_remaining']} days remaining"
    )
elif state["state"] == "LIVE_WINDOW":
    st.success("🟢 Observation window LIVE (15–22 Feb 2026)")
else:
    st.info("🔵 Observation window closed")

st.divider()

# =============================
# Layout
# =============================
col1, col2 = st.columns(2)

# =============================
# LEFT: Accuracy Meter (Placeholder)
# =============================
with col1:
    st.subheader("📊 ΛCDM vs DVDH Accuracy Meter")
    st.progress(0.0)
    st.caption("Residual-based accuracy comparison (inactive placeholder)")

# =============================
# RIGHT: Θ_obs Tracker
# =============================
with col2:
    st.subheader("🧭 Θ_obs — DSI Projection Tracker")

    st.markdown(
        """
        Θ_obs evaluates **relative geometric structure**,  
        not signal strength.
        """
    )

    st.markdown("**Input: Consecutive Spike Timing (milliseconds)**")

    t1 = st.number_input("Δt₁ (ms)", min_value=0.1, value=10.0, step=0.1)
    t2 = st.number_input("Δt₂ (ms)", min_value=0.1, value=16.0, step=0.1)

    # ---- Core Math ----
    phi = (1 + math.sqrt(5)) / 2
    ratio = t2 / t1 if t1 > 0 else 0.0
    theta_obs = abs(ratio - phi)

    st.divider()

    st.metric("Spike Ratio (Δt₂ / Δt₁)", f"{ratio:.4f}")
    st.metric("Golden Ratio φ", f"{phi:.4f}")
    st.metric("Θ_obs = |ratio − φ|", f"{theta_obs:.6f}")

    # ---- Interpretation ----
    if theta_obs < 0.02:
        st.success("🟢 High geometric coherence (Θ ≪ 1)")
    elif theta_obs < 0.05:
        st.warning("🟡 Marginal coherence")
    else:
        st.info("🔵 No geometric alignment detected")

    st.caption(
        "Θ_obs is a dimensionless diagnostic deviation metric. "
        "Lower values indicate closer geometric alignment."
    )

st.divider()

# =============================
# Email Alert Configuration
# =============================
st.markdown("### 📧 Email Alert Configuration")

alert_threshold = st.number_input(
    "Alert if Θ_obs falls below:",
    min_value=0.0001,
    value=0.02,
    step=0.001,
    format="%.4f"
)

recipient_email = st.text_input("Recipient Email")

# ---- Session state init ----
if "alert_sent" not in st.session_state:
    st.session_state.alert_sent = False

if "last_alert_time" not in st.session_state:
    st.session_state.last_alert_time = None

if "last_telegram_alert" not in st.session_state:
    st.session_state.last_telegram_alert = None

if "theta_history" not in st.session_state:
    st.session_state.theta_history = []

# =============================
# Alert Functions
# =============================
def send_email_alert(theta_value):
    email_user = os.getenv("EMAIL_USER")
    email_pass = os.getenv("EMAIL_PASS")

    if not email_user or not email_pass:
        st.error("Email credentials not configured.")
        return False

    msg = EmailMessage()
    msg["Subject"] = "DVDH LIVE Θ Alert Triggered"
    msg["From"] = email_user
    msg["To"] = recipient_email

    msg.set_content(
        f"""
LIVE Θ threshold crossed.

Θ_obs = {theta_value:.6f}

This alert is automatically generated by DVDH Diagnostic Dashboard.
No physical claim is implied.
"""
    )

    context = ssl.create_default_context()

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
            server.login(email_user, email_pass)
            server.send_message(msg)
        return True
    except Exception:
        return False


def send_telegram_alert(theta_value):
    try:
        token = st.secrets["TELEGRAM_TOKEN"]
        chat_id = st.secrets["TELEGRAM_CHAT_ID"]
    except KeyError:
        st.error("Telegram credentials not configured.")
        return False

    message = f"🚨 LIVE Θ Alert\nΘ_obs = {theta_value:.6f}"

    url = f"https://api.telegram.org/bot{token}/sendMessage"

    try:
        r = requests.post(
            url,
            json={"chat_id": chat_id, "text": message},
            timeout=2
        )
        return r.status_code == 200
    except Exception as e:
        st.error(f"Telegram send failed: {e}")
        return False

# =============================
# Ratio Analysis Panel
# =============================
st.subheader("📐 Ratio Structure Panel")

deviation_percent = abs((ratio - phi) / phi) * 100

c1, c2, c3 = st.columns(3)
c1.metric("Observed Ratio", f"{ratio:.4f}")
c2.metric("Golden Ratio φ", f"{phi:.4f}")
c3.metric("Deviation (%)", f"{deviation_percent:.2f}%")

st.divider()
st.markdown("**Geometric Consistency Band**")

if deviation_percent < 1.5:
    st.success("🟢 Strong Fibonacci alignment")
elif deviation_percent < 3.5:
    st.warning("🟡 Weak / borderline alignment")
else:
    st.info("🔵 No harmonic structure detected")

st.divider()
st.markdown("**Ratio Summary Table**")

st.table({
    "Metric": [
        "Δt₁ (ms)",
        "Δt₂ (ms)",
        "Δt₂ / Δt₁",
        "φ (Golden Ratio)",
        "Deviation (%)"
    ],
    "Value": [
        f"{t1:.2f}",
        f"{t2:.2f}",
        f"{ratio:.4f}",
        f"{phi:.4f}",
        f"{deviation_percent:.2f}"
    ]
})

st.caption(
    "Ratio panel reports purely mathematical structure. "
    "No physical interpretation is implied."
)

st.divider()
st.markdown("### 🔴 LIVE Θ Tracker")

# ---- Live Mode Switch ----
live_mode = st.toggle("Enable LIVE Θ tracking", value=False)

live_placeholder = st.empty()

# ---- Live Update Logic ----
if live_mode:
    with live_placeholder.container():

        st.info("LIVE MODE active — updating Θ_obs")

        drift = random.uniform(-0.5, 0.5)
        t2_live = max(0.1, t2 + drift)

        ratio_live = t2_live / t1
        theta_live = abs(ratio_live - phi)

        # ---- Display always ----
        st.metric("LIVE Θ_obs", f"{theta_live:.6f}")

        if theta_live < 0.02:
            st.success("🟢 Live geometric coherence")
        elif theta_live < 0.05:
            st.warning("🟡 Marginal live alignment")
        else:
            st.info("🔵 No live alignment")

        # ---- Email Cooldown (1 hour) ----
        if recipient_email and theta_live < alert_threshold:

            now = datetime.datetime.utcnow()

            if (
                st.session_state.last_alert_time is None
                or (now - st.session_state.last_alert_time).total_seconds() >= 3600
            ):
                if send_email_alert(theta_live):
                    st.session_state.last_alert_time = now
                    st.success("📧 Alert email sent (1-hour cooldown active).")

        # ---- Telegram Cooldown (60 sec) ----
        if theta_live < alert_threshold:

            now = datetime.datetime.utcnow()

            if (
                st.session_state.last_telegram_alert is None
                or (now - st.session_state.last_telegram_alert).total_seconds() >= 60
            ):
                if send_telegram_alert(theta_live):
                    st.session_state.last_telegram_alert = now
                    st.success("📲 Telegram alert sent.")

        # ---- Append history ----
        st.session_state.theta_history.append(theta_live)
        if len(st.session_state.theta_history) > 50:
            st.session_state.theta_history.pop(0)

        time.sleep(1.5)
        st.rerun()
else:
    st.caption("LIVE Θ tracker is paused.")

# =============================
# Footer
# =============================
st.caption(
    "DVDH–DSI Simulation Project • MIT License • Diagnostic Use Only"
)
